export const ActionTypes = {
  USER_SIGN_UP: 'USER_SIGN_UP',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',

  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  GET_FORGOT_PASSWORD_OTP: 'GET_FORGOT_PASSWORD_OTP',
  GET_FORGOT_PASSWORD_OTP_SUCCESS: 'GET_FORGOT_PASSWORD_OTP_SUCCESS',
  GET_FORGOT_PASSWORD_OTP_FAILURE: 'GET_FORGOT_PASSWORD_OTP_FAILURE',

  VERIFY_FORGOT_PASSWORD_OTP: 'VERIFY_FORGOT_PASSWORD_OTP',
  VERIFY_FORGOT_PASSWORD_OTP_SUCCESS: 'VERIFY_FORGOT_PASSWORD_OTP_SUCCESS',
  VERIFY_FORGOT_PASSWORD_OTP_FAILURE: 'VERIFY_FORGOT_PASSWORD_OTP_FAILURE',
  
  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  RESET_FORGOT_STATUS: 'RESET_FORGOT_STATUS',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  GET_EMISSION_LIST: 'GET_EMISSION_LIST',
  GET_EMISSION_LIST_SUCCESS: 'GET_EMISSION_LIST_SUCCESS',
  GET_EMISSION_LIST_FAILURE: 'GET_EMISSION_LIST_FAILURE',

  LIST_FACILITIES: 'LIST_FACILITIES',
  LIST_FACILITIES_SUCCESS: 'LIST_FACILITIES_SUCCESS',
  LIST_FACILITIES_FAILURE: 'LIST_FACILITIES_FAILURE',

  ADD_STATIONARY_COMBUSTION: 'ADD_STATIONARY_COMBUSTION',
  ADD_STATIONARY_COMBUSTION_SUCCESS: 'ADD_STATIONARY_COMBUSTION_SUCCESS',
  ADD_STATIONARY_COMBUSTION_FAILURE: 'ADD_STATIONARY_COMBUSTION_FAILURE',

  ADD_MOBILE_COMBUSTION: 'ADD_MOBILE_COMBUSTION',
  ADD_MOBILE_COMBUSTION_SUCCESS: 'ADD_MOBILE_COMBUSTION_SUCCESS',
  ADD_MOBILE_COMBUSTION_FAILURE: 'ADD_MOBILE_COMBUSTION_FAILURE',

  ADD_TRANSPORTATION_COMBUSTION: 'ADD_TRANSPORTATION_COMBUSTION',
  ADD_TRANSPORTATION_COMBUSTION_SUCCESS: 'ADD_TRANSPORTATION_COMBUSTION_SUCCESS',
  ADD_TRANSPORTATION_COMBUSTION_FAILURE: 'ADD_TRANSPORTATION_COMBUSTION_FAILURE',

  RESET_ADD_COMBUSTION_STATUS: 'RESET_ADD_COMBUSTION_STATUS',

  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',

  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

  GET_INDUSTRY_TYPES: 'GET_INDUSTRY_TYPES',
  GET_INDUSTRY_TYPES_SUCCESS: 'GET_INDUSTRY_TYPES_SUCCESS',
  GET_INDUSTRY_TYPES_FAILURE: 'GET_INDUSTRY_TYPES_FAILURE',

  GET_COUNTRY_LIST: 'GET_COUNTRY_LIST',
  GET_COUNTRY_LIST_SUCCESS: 'GET_COUNTRY_LIST_SUCCESS',
  GET_COUNTRY_LIST_FAILURE: 'GET_COUNTRY_LIST_FAILURE',

  GET_EMISSION_YEAR: 'GET_EMISSION_YEAR',
  GET_EMISSION_YEAR_SUCCESS: 'GET_EMISSION_YEAR_SUCCESS',
  GET_EMISSION_YEAR_FAILURE: 'GET_EMISSION_YEAR_FAILURE',

  GET_EMISSION_TYPES: 'GET_EMISSION_TYPES',
  GET_EMISSION_TYPES_SUCCESS: 'GET_EMISSION_TYPES_SUCCESS',
  GET_EMISSION_TYPES_FAILURE: 'GET_EMISSION_TYPES_FAILURE',

  GET_EMISSION_REGION: 'GET_EMISSION_REGION',
  GET_EMISSION_REGION_SUCCESS: 'GET_EMISSION_REGION_SUCCESS',
  GET_EMISSION_REGION_FAILURE: 'GET_EMISSION_REGION_FAILURE',
};

