export const ActionTypes = {
  USER_SIGN_UP: 'USER_SIGN_UP',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',

  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  GET_FORGOT_PASSWORD_OTP: 'GET_FORGOT_PASSWORD_OTP',
  GET_FORGOT_PASSWORD_OTP_SUCCESS: 'GET_FORGOT_PASSWORD_OTP_SUCCESS',
  GET_FORGOT_PASSWORD_OTP_FAILURE: 'GET_FORGOT_PASSWORD_OTP_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  RESET_FORGOT_STATUS: 'RESET_FORGOT_STATUS',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  USER_SIGN_UP: 'USER_SIGN_UP',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_FAILURE: 'USER_SIGN_UP_FAILURE',

  REFRESH_TOKEN: 'REFRESH_TOKEN',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',

  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',

  GET_INDUSTRY_TYPES: 'GET_INDUSTRY_TYPES',
  GET_INDUSTRY_TYPES_SUCCESS: 'GET_INDUSTRY_TYPES_SUCCESS',
  GET_INDUSTRY_TYPES_FAILURE: 'GET_INDUSTRY_TYPES_FAILURE',

  GET_COUNTRY_LIST: 'GET_COUNTRY_LIST',
  GET_COUNTRY_LIST_SUCCESS: 'GET_COUNTRY_LIST_SUCCESS',
  GET_COUNTRY_LIST_FAILURE: 'GET_COUNTRY_LIST_FAILURE'
};

