export const ActionTypes = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  GET_FORGOT_PASSWORD_OTP: 'GET_FORGOT_PASSWORD_OTP',
  GET_FORGOT_PASSWORD_OTP_SUCCESS: 'GET_FORGOT_PASSWORD_OTP_SUCCESS',
  GET_FORGOT_PASSWORD_OTP_FAILURE: 'GET_FORGOT_PASSWORD_OTP_FAILURE',

  VERIFY_FORGOT_PASSWORD_OTP: 'VERIFY_FORGOT_PASSWORD_OTP',
  VERIFY_FORGOT_PASSWORD_OTP_SUCCESS: 'VERIFY_FORGOT_PASSWORD_OTP_SUCCESS',
  VERIFY_FORGOT_PASSWORD_OTP_FAILURE: 'VERIFY_FORGOT_PASSWORD_OTP_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE'

};

export const STATUS = {
  IDLE: 'idle',
  RUNNING: 'running',
  READY: 'ready',
  SUCCESS: 'success',
  ERROR: 'error'
};

const API_BASE_URL = 'https://api-shop.shopsapp.org/admin';

export const APIEndpoints = {
  LOGIN: `${API_BASE_URL}/login`,
  FORGOT_PASSWORD: `${API_BASE_URL}/forgot-password`,
  VERIFY_OTP: `${API_BASE_URL}/forgot-password/verify`,
  CHANGE_PASSWORD: `${API_BASE_URL}/forgot-password/change`
}
